services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/ollama
      - ./run-ollama.sh:/run-ollama.sh
    pull_policy: always
    tty: true
    restart: no
    entrypoint: ["/usr/bin/bash", "run-ollama.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  vueapp:
    image: kand7dev99/kand7dev-projects:ollama3-vuejs-nvidia
    container_name: vue-frontend
    ports:
      - 8080:8080

volumes:
  ollama: